### ISSUE TITLE
Mantle API docs

### ISSUE THREAD

**Issue by mdsitton** [Bizarrus/AMD-Mantle#1]
AMD has recently released the api reference, but no headers. So thought you might be interested in this if you are planning to continue this.

http://www.amd.com/Documents/Mantle-Programming-Guide-and-API-Reference.pdf

**Comment by Bizarrus** [comment]
wow, big thanks dude :) :+1: 

already had try contact AMD more than once for access. its irrelevant if you asking for education purposes - No answers.

**Comment by mdsitton** [comment]
Yeah no problem.

I've also since found this guy. He already has a header going and stuff kind of working.
https://github.com/Overv/MantleHelloTriangle

Went looking into it and the main thing I can see being an issue is getting sharers setup. Since you need to give mantle what the docs call a subset of AMD IL(AMD Intermediate Language).
Here is the AMD IL spec:
http://developer.amd.com/wordpress/media/2012/10/AMD_Intermediate_Language_%28IL%29_Specification_v2.pdf

I'm curious if this tool could help with that(I'm not on windows currently to be able to test it to see if it can output AMD IL):
http://developer.amd.com/tools-and-sdks/graphics-development/gpu-shaderanalyzer/

I have also found a few AMD IL tutorials from the scope of GPGPU using an amd library called the Compute Abstraction Layer. http://sysmagazine.com/posts/138954/
And another (in russian) http://habrahabr.ru/post/138954/ 

In the mantle docs i think there is one AMD IL example that deals with msaa?

**Comment by mdsitton** [comment]
Alright so booted into windows, that tool does output AMD IL :)

**Comment by Bizarrus** [comment]
I will check these links, very interesting.

i've seen you have a fork of Frets on Fire - I like that game :) 2013 i've started a clone for iOS, but currently i have no Mac for that.

I want to understand the structure of the Mantle API to create a public basic API. The goal is for other game engines (for example libGDX) offer an extra Java-Wrapper which is based on Mantle.

You've helped me a lot with the documentation/reference

**Comment by mdsitton** [comment]
Haha yeah that fofix-rewrite repo isn't really a fork. However I am a developer on FoFiX(https://github.com/fofix/fofix) as well, even if development has slowed to a halt.

Actually me an another guy started last week working on a frets on fire like game. Its C++ with OpenGL. The repo isn't public yet because we wan't to figure out a good name first...

Only new thing since my previous comment, I may have some very basic AMD IL shaders figured out.

Vertex shader: copy vertex position to output
Fragment/Pixel shader: Change output color to red

```
il_vs_2_0
dcl_input_generic v0
dcl_output_position o0
mov o0, v0
ret_dyn
end

il_ps_2_0
dcl_output_generic o0
dcl_literal l0, 1.0, 0.0, 0.0, 1.0
mov o0, l0
end
```

**Comment by Bizarrus** [comment]
See the last commit, here is the complete `API Specification/Documentation` from AMD :)
